lang_name: "Українська"
title: "Carft Rom"
description: "CraftRom OS - це кастомний ROM на AOSP з Google-додатками. Наша мета - надати найвищу стабільність та функціональність."
donate: "Пожертвувати"
contribute: "Співпрацювати"
