lang_name: "English"
title: "Carft Rom"
description: "CraftRom OS is a custom ROM based on AOSP with built-in Google apps. Our goal is to provide the highest stability and functionality to meet users' needs."
donate: "Donate"
contribute: "Contribute"
